### ISSUE TITLE
[BUG] - Black outlines near objects

### ISSUE THREAD

**Issue by sanek7814** [rj200/Glamarye_Fast_Effects_for_ReShade#12]
In the game Quantum Break, I noticed such a sharpness bug that black outlines appear on some objects, especially on some white text for example, on the monitors that are in the game. I bring two photos for demonstration.

https://i.ibb.co/p477qSZ/1.png - your shader  with a sharpness strength of 2
https://i.ibb.co/nms5Nr0/1.png - CAS shader  with a value of 8

In the screenshots, this can be seen with a detailed approximation (blue circle)  but in the game it can be seen very noticeably. It catches the eye.

**Comment by pepper-jelly** [comment]
@sanek7814 it's simple unsharp mask, just lower strength or use another sharpener with lower radius(luma sharpen, cas)

**Comment by sanek7814** [comment]
I'd love to, but I'm used to your shader, time after time it shows great results against cas or luma.

**Comment by rj200** [comment]
Well at high strength any sharpen algorithm will create some halos or outlines - that's basically how sharpen works. 

Both have halos around the blue circle. CAS has a green halo and Glamayre has a black one. That's because Glamayre is sharpening the brightness without changing the colour, while (I assume) CAS is sharpening red green and blue separately. I made Glamayre sharpen brightness after seeing colour artefacts - for example on the menu screen of Horizon Zero Dawn. Actually you can see an example of an ugly colour artefact in your CAS screenshot - notice the bright green pixels at the edge of the orange wire above the monitor.

Perhaps Glamayre is oversharpenning very dark pixels (i.e. the dark grey monitor) too much relative to bright ones. 

I'm staring at my code and I think I have an idea that might help... will experiment....

**Comment by rj200** [comment]
I've tweaked sharpen so it won't push a pixel all the way to black. I hope it looks better for you in Quantum Break. I haven't got it to test with myself.

https://github.com/rj200/Glamarye_Fast_Effects_for_ReShade/commit/286f5cd55a44ed1ea6411a7366b305b9bc66aa8d

**Comment by sanek7814** [comment]
This can be called version 4.6.2
By the way, I checked the new version in Deus Ex Human Revolution, the really black contours on the edges of the weapon became less noticeable.

**Comment by odikzz2** [comment]
Can you add an option that exclude sharpening the distance i can also see this black outlines in sims 4 far away.

**Comment by sanek7814** [comment]
The problem I think is solved.
