### ISSUE TITLE
[Suggestion] - replace FXAA with SMAA

### ISSUE THREAD

**Issue by sanek7814** [rj200/Glamarye_Fast_Effects_for_ReShade#16]
I think everything is clear here, FXAA blurs the font in the game, often it disturbs the eyes, so I propose to replace FXAA to SMAA, which can be put in anti-aliasing mode that will not blur the fonts in the game.
I know that SMAA shader can be included separately from your shader, it's more of a suggestion for convenience.

**Comment by rj200** [comment]
I don't really have time nor interest in turning it into a do-everything shader with multiple algorithms for each effect. The point of my unique Fast FXAA is that it's faster than FXAA and SMAA - it's not trying to look as good as them. I was trying to get games running faster at 4k with a gaming laptop plugged into a TV! 

If you prefer quality over speed then I suggest just running SMAA separately on older games. 

Newer games usually have TAA, FSR2 and/or DLSS2 built in, which will look much better (yes even with up-scaling, quality mode of FSR2 and DLSS normally looks better than native resolution+FXAA due to the use of temporal jitter.)
