### ISSUE TITLE
Depth likely not detected

### ISSUE THREAD

**Issue by Gunlaus** [rj200/Glamarye_Fast_Effects_for_ReShade#2]
I'm using a modified openGL found here: [https://reshade.me/forum/general-discussion/5391-release-pcsx2-with-depth-buffer-access](url) for PCSX2 and while I've got the depth buffer working perfectly with other effects, with your effects it doesn't seem to be working at all. Selecting depth just shows up as white on the screen. Any clue on how to solve this?

**Comment by rj200** [comment]
Sorry, I don't know. I've never used PCSX2. 

It is possible you just need to configure the depth buffer. Glamayre uses the default reshade depth buffer settings. See Marty's guide to help set it up: https://github.com/martymcmodding/ReShade-Guide/wiki/The-Depth-Buffer. 

Which other effects work where Glamayre doesn't? Does DisplayDepth.fx work okay? I know some other shaders do their own depth buffer setup, instead of using ReShade's setup so maybe that's why they work and Glamayre doesn't?
