### ISSUE TITLE
Suggestion for reducing AO bleeding through fog/mist etc 

### ISSUE THREAD

**Issue by vrnord** [rj200/Glamarye_Fast_Effects_for_ReShade#5]
The sliders for AO distance and brightness aren't really helping reduce AO from bleeding through fog, smoke and mist in my modded Skyrim, and Reveil.fx has a relatively high performance cost and doesn't entirely fix it either.  However, I notice that most fog/mist/smoke ends up looking grey in-game, and if translucent it has the effect of making whatever is behind it look quite desaturated as well.  

So if one could tell your AO to disregard screen areas below "x" saturation threshold via a saturation slider that might greatly improve the bleed-through situation.

**Comment by rj200** [comment]
Maybe it could help specific games/locations, but I don't think it can work well in most scenes. I did briefly experiment with that idea the early days of glamayre. 2 problems:

* Grey walls don't get much AO - grey objects sort of need it more than colourful ones because colourful objects stand out more from their surroundings anyway making their shape clearer.
* Most games actually use various colours of fog/mist based on location or weather. 

Option: use the game's built-in AO instead and turning off glamayre's option. The checkbox for "Cinematic DOF safe mode" might help too - it disables local AO but still allows some of the large-scale AO from the Fake GI effect, but smoothed.

I've thought about doing some global measurement of the contrast/depth ratio but will be imperfect, complicated and probably slow.

The real fix is to apply the shader earlier in the games pipeline before fog is added. This should be possible using the new plugin mechanism in ReShade 6.0. However, no-one has written a plugin to do it yet.

**Comment by vrnord** [comment]
I appreciate the reply!
